version: "3"
services:
  mysql:
    image: mysql
    container_name: gogs_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwer4321
      MYSQL_DATABASE: gogs
    ports:
      - "10036:3306"
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/db:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
    networks: 
      gogs_app:
        aliases:
          - mysql
  gogs:
    image: gogs/gogs
    container_name: gogs
    restart: always
    ports:
      - "8190:3000"
      - "10022:22"
    depends_on:
      - mysql
    volumes:
      - ./data:/data
    networks: 
      gogs_app:
        aliases:
          - gogs_main
  etcd:
    hostname: etcd
    image: bitnami/etcd:3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "12379:2379"
      - "12380:2380"
    volumes:
      - "./etcd/data:/opt/bitnami/etcd/data"
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
      - "ETCD_NAME=node1"
      - "ETCD_DATA_DIR=/opt/bitnami/etcd/data"
     networks:
      gogs_app:
        aliases:
          - etcd
 networks:
  gogs_app:
    driver: bridge
